# Generated by Django 2.2.7 on 2019-12-03 21:44

import api.utils
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='id',
        ),
        migrations.AddField(
            model_name='people',
            name='_id',
            field=models.CharField(default=api.utils.url_id_gen, max_length=24),
        ),
        migrations.AlterField(
            model_name='people',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
