# Generated by Django 2.2.7 on 2019-12-03 00:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
