# Generated by Django 2.2.7 on 2019-12-03 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_people_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='employee_friends', to='api.People')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='api.People')),
            ],
        ),
    ]
