# Generated by Django 2.2.7 on 2019-12-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191203_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='greeting',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
