# Generated by Django 2.2.7 on 2019-12-03 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191203_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='friends',
        ),
    ]
